/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as DataRouteImport } from './routes/data'
import { Route as EmberRouteImport } from './routes/ember'
import { Route as EventsRouteImport } from './routes/events'
import { Route as KnowledgeRouteImport } from './routes/knowledge'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as SimulatorRouteImport } from './routes/simulator'
import { Route as ApiEmberRouteImport } from './routes/api/ember'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const DataRoute = DataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => rootRouteImport,
} as any)
const EmberRoute = EmberRouteImport.update({
  id: '/ember',
  path: '/ember',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeRoute = KnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulatorRoute = SimulatorRouteImport.update({
  id: '/simulator',
  path: '/simulator',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEmberRoute = ApiEmberRouteImport.update({
  id: '/api/ember',
  path: '/api/ember',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/community': typeof CommunityRoute
  '/data': typeof DataRoute
  '/ember': typeof EmberRoute
  '/events': typeof EventsRoute
  '/knowledge': typeof KnowledgeRoute
  '/onboarding': typeof OnboardingRoute
  '/simulator': typeof SimulatorRoute
  '/api/ember': typeof ApiEmberRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/community': typeof CommunityRoute
  '/data': typeof DataRoute
  '/ember': typeof EmberRoute
  '/events': typeof EventsRoute
  '/knowledge': typeof KnowledgeRoute
  '/onboarding': typeof OnboardingRoute
  '/simulator': typeof SimulatorRoute
  '/api/ember': typeof ApiEmberRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/community': typeof CommunityRoute
  '/data': typeof DataRoute
  '/ember': typeof EmberRoute
  '/events': typeof EventsRoute
  '/knowledge': typeof KnowledgeRoute
  '/onboarding': typeof OnboardingRoute
  '/simulator': typeof SimulatorRoute
  '/api/ember': typeof ApiEmberRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/community'
    | '/data'
    | '/ember'
    | '/events'
    | '/knowledge'
    | '/onboarding'
    | '/simulator'
    | '/api/ember'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/community'
    | '/data'
    | '/ember'
    | '/events'
    | '/knowledge'
    | '/onboarding'
    | '/simulator'
    | '/api/ember'
  id:
    | '__root__'
    | '/'
    | '/community'
    | '/data'
    | '/ember'
    | '/events'
    | '/knowledge'
    | '/onboarding'
    | '/simulator'
    | '/api/ember'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CommunityRoute: typeof CommunityRoute
  DataRoute: typeof DataRoute
  EmberRoute: typeof EmberRoute
  EventsRoute: typeof EventsRoute
  KnowledgeRoute: typeof KnowledgeRoute
  OnboardingRoute: typeof OnboardingRoute
  SimulatorRoute: typeof SimulatorRoute
  ApiEmberRoute: typeof ApiEmberRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data': {
      id: '/data'
      path: '/data'
      fullPath: '/data'
      preLoaderRoute: typeof DataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ember': {
      id: '/ember'
      path: '/ember'
      fullPath: '/ember'
      preLoaderRoute: typeof EmberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge': {
      id: '/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof KnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulator': {
      id: '/simulator'
      path: '/simulator'
      fullPath: '/simulator'
      preLoaderRoute: typeof SimulatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ember': {
      id: '/api/ember'
      path: '/api/ember'
      fullPath: '/api/ember'
      preLoaderRoute: typeof ApiEmberRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CommunityRoute: CommunityRoute,
  DataRoute: DataRoute,
  EmberRoute: EmberRoute,
  EventsRoute: EventsRoute,
  KnowledgeRoute: KnowledgeRoute,
  OnboardingRoute: OnboardingRoute,
  SimulatorRoute: SimulatorRoute,
  ApiEmberRoute: ApiEmberRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
